'use client'

import { useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { cn, formatCurrencyFull, formatMonth } from '@/lib/utils'

type RevenueRow = { company_name: string; month: string; actual: number; budget: number }
type Goal = { revenue_goal: number; revenue_stretch_goal: number } | null
type Proposal = { total_revenue: number; weighted_likelihood: number }
interface Props { year: number; months: string[]; revenue: RevenueRow[]; goal: Goal; proposals: Proposal[] }

export function AnalysisClient({ year, months, revenue, goal, proposals }: Props) {
  const [fromMonth, setFromMonth] = useState(months[0])
  const [toMonth, setToMonth] = useState(months[months.length - 1])
  const filteredMonths = useMemo(() => months.filter(month => month >= fromMonth && month <= toMonth), [months, fromMonth, toMonth])
  const revenueByMonth = filteredMonths.map(month => revenue.filter(row => row.month === month).reduce((sum, row) => sum + Number(row.actual ?? row.budget ?? 0), 0))
  const totalRevenue = revenueByMonth.reduce((sum, amount) => sum + amount, 0)
  const goalPct = goal ? Math.min(100, totalRevenue / goal.revenue_goal * 100) : null
  const weightedPipeline = proposals.reduce((sum, proposal) => sum + Number(proposal.total_revenue) * proposal.weighted_likelihood / 100, 0)
  const clientRows = Object.values(revenue.filter(row => filteredMonths.includes(row.month)).reduce<Record<string, number>>((clients, row) => ({ ...clients, [row.company_name]: (clients[row.company_name] || 0) + Number(row.actual ?? row.budget ?? 0) }), {})).sort((a, b) => b - a)
  const clientAmounts = revenue.filter(row => filteredMonths.includes(row.month)).reduce<Record<string, number>>((clients, row) => ({ ...clients, [row.company_name]: (clients[row.company_name] || 0) + Number(row.actual ?? row.budget ?? 0) }), {})
  const chartData = filteredMonths.map((month, index) => ({ month: formatMonth(month), Revenue: revenueByMonth[index] }))

  return <div className="min-h-screen bg-[var(--background)] py-6 px-4"><div className="max-w-6xl mx-auto space-y-4">
    <div className="flex items-center justify-between"><div><h1 className="font-heading text-2xl text-[var(--deep-teal)]">Revenue Analysis</h1><p className="text-sm text-[var(--muted-foreground)] mt-0.5">{year} overview</p></div><div className="flex gap-1">{[year - 1, year, year + 1].map(value => <a key={value} href={`/analysis/annual?year=${value}`} className={cn('px-3 py-1.5 rounded-lg text-xs font-medium', value === year ? 'bg-[var(--deep-teal)] text-white' : 'bg-[var(--light-mint)] text-[var(--deep-teal)]')}>{value}</a>)}</div></div>
    <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm px-5 py-3 flex items-center gap-4 flex-wrap"><p className="text-xs font-medium text-[var(--muted-foreground)]">Filter by month range:</p><select value={fromMonth} onChange={event => setFromMonth(event.target.value)} className="border border-[var(--border)] rounded-lg px-2 py-1 text-xs">{months.map(month => <option key={month} value={month}>{formatMonth(month)}</option>)}</select><span className="text-xs">to</span><select value={toMonth} onChange={event => setToMonth(event.target.value)} className="border border-[var(--border)] rounded-lg px-2 py-1 text-xs">{months.map(month => <option key={month} value={month}>{formatMonth(month)}</option>)}</select><button onClick={() => { setFromMonth(months[0]); setToMonth(months[months.length - 1]) }} className="text-xs text-[var(--bright-teal)] hover:underline">Reset</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Metric label="Total Revenue" value={formatCurrencyFull(totalRevenue)} color="text-[var(--deep-teal)]" />{goalPct !== null && <Metric label="Revenue Goal Progress" value={`${Math.round(goalPct)}%`} color="text-[var(--bright-teal)]" />}{<Metric label="Pipeline" value={formatCurrencyFull(weightedPipeline)} sub="weighted" color="text-purple-600" />}</div>
    {goal && goalPct !== null && <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm px-5 py-4"><div className="flex items-center justify-between mb-2"><p className="text-sm font-medium text-[var(--deep-teal)]">Revenue Goal Progress</p><p className="text-sm font-semibold text-[var(--bright-teal)]">{Math.round(goalPct)}%</p></div><div className="w-full h-3 bg-[var(--border)] rounded-full overflow-hidden"><div className="h-full rounded-full bg-[var(--bright-teal)]" style={{ width: `${goalPct}%` }} /></div><div className="flex justify-between mt-1.5 text-xs text-[var(--muted-foreground)]"><span>{formatCurrencyFull(totalRevenue)} tracked</span><span>{formatCurrencyFull(goal.revenue_goal)} goal</span></div></div>}
    <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm px-5 pt-5 pb-4"><h2 className="font-heading text-base text-[var(--deep-teal)] mb-4">Monthly Revenue</h2><ResponsiveContainer width="100%" height={240}><AreaChart data={chartData} margin={{ top: 4, right: 4, left: -16, bottom: 0 }}><defs><linearGradient id="revenue-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0c6b78" stopOpacity={0.16} /><stop offset="95%" stopColor="#0c6b78" stopOpacity={0} /></linearGradient></defs><CartesianGrid horizontal vertical={false} stroke="#f1f5f9" /><XAxis dataKey="month" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={value => `$${(value / 1000).toFixed(0)}k`} /><Tooltip formatter={value => formatCurrencyFull(Number(value || 0))} /><Area type="monotone" dataKey="Revenue" stroke="#0c6b78" strokeWidth={2} fill="url(#revenue-gradient)" dot={false} activeDot={{ r: 4, fill: '#0c6b78', strokeWidth: 0 }} /></AreaChart></ResponsiveContainer></div>
    <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm overflow-hidden"><div className="px-5 py-3 border-b border-[var(--border)]"><h2 className="font-heading text-base text-[var(--deep-teal)]">Revenue by Client</h2></div><table className="w-full text-sm"><thead><tr className="bg-[var(--light-mint)] text-[var(--muted-foreground)] text-[11px] uppercase tracking-wide"><th className="px-5 py-2 text-left">Client</th><th className="px-5 py-2 text-right">Revenue</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{Object.entries(clientAmounts).sort(([, a], [, b]) => b - a).map(([name, amount]) => <tr key={name}><td className="px-5 py-2.5 font-medium">{name}</td><td className="px-5 py-2.5 text-right">{formatCurrencyFull(amount)}</td></tr>)}{clientRows.length === 0 && <tr><td colSpan={2} className="px-5 py-6 text-center text-sm text-[var(--muted-foreground)]">No revenue data for this period.</td></tr>}</tbody></table></div>
  </div></div>
}

function Metric({ label, value, sub, color }: { label: string; value: string; sub?: string; color: string }) { return <div className="bg-white rounded-xl border border-[var(--border)] shadow-sm p-4"><p className="text-[10px] text-[var(--muted-foreground)] uppercase tracking-wide">{label}</p><p className={`text-xl font-semibold mt-1 ${color}`}>{value}</p>{sub && <p className="text-[10px] text-[var(--muted-foreground)] mt-0.5">{sub}</p>}</div> }
