'use client'

import { FormEvent, useMemo, useState } from 'react'
import Image from 'next/image'
import { BarChart3, ExternalLink, Instagram, Linkedin, Mic2, Users, Youtube } from 'lucide-react'
import { BRAND_CHANNELS } from '@/lib/brand-channels'

type Stat = { channel_id: string; logged_on: string; followers: number | null; impressions: number | null; views: number | null; source: string; note: string | null }
const icons: Record<string, typeof Youtube> = { YouTube: Youtube, Instagram, LinkedIn: Linkedin, Podcast: Mic2, Community: Users, X: BarChart3 }
const number = (value: number | null | undefined) => new Intl.NumberFormat('en-US', { notation: value && value >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value || 0)

export function BrandStatsClient({ stats, connectedChannels }: { stats: Stat[]; connectedChannels: string[] }) {
  const [form, setForm] = useState({ channel_id: 'linkedin', logged_on: new Date().toISOString().slice(0, 10), followers: '', impressions: '', views: '', note: '' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const byChannel = useMemo(() => BRAND_CHANNELS.map(channel => ({ channel, history: stats.filter(stat => stat.channel_id === channel.id).sort((a, b) => a.logged_on.localeCompare(b.logged_on)) })), [stats])
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch('/api/brand-stats/manual', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); setMessage(response.ok ? 'Saved. Refresh the page to see the new entry.' : 'Could not save this entry.') }

  return <div className="min-h-screen bg-[var(--background)] py-6 px-4"><div className="max-w-[1500px] mx-auto space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[var(--bright-teal)] font-semibold">MMG Homebase</p><h1 className="font-heading text-3xl text-[var(--deep-teal)] mt-1">Brand Stats</h1><p className="text-sm text-[var(--muted-foreground)] mt-1">Daily audience, impressions, and views across your brand.</p></div><div className="rounded-xl bg-white border border-[var(--border)] px-4 py-3"><p className="text-[10px] uppercase tracking-wide text-[var(--muted-foreground)]">Tracking cadence</p><p className="text-sm font-semibold text-[var(--deep-teal)]">Daily snapshots</p></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{byChannel.map(({ channel, history }) => <ChannelCard key={channel.id} channel={channel} history={history} connected={connectedChannels.includes(channel.id)} />)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[0.95fr_2.05fr] gap-5"><form onSubmit={submit} className="bg-white rounded-2xl border border-[var(--border)] shadow-sm p-5 space-y-4"><div><h2 className="font-heading text-lg text-[var(--deep-teal)]">Log Daily Stats</h2><p className="text-xs text-[var(--muted-foreground)] mt-1">Use this for channels that are not connected yet.</p></div><label className="block text-xs font-medium">Channel<select value={form.channel_id} onChange={event => setForm({ ...form, channel_id: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm">{BRAND_CHANNELS.map(channel => <option key={channel.id} value={channel.id}>{channel.name} · {channel.platform}</option>)}</select></label><label className="block text-xs font-medium">Date<input type="date" value={form.logged_on} onChange={event => setForm({ ...form, logged_on: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></label><div className="grid grid-cols-3 gap-2">{(['followers', 'impressions', 'views'] as const).map(field => <label key={field} className="block text-xs font-medium capitalize">{field}<input type="number" min="0" value={form[field]} onChange={event => setForm({ ...form, [field]: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-sm" /></label>)}</div><label className="block text-xs font-medium">Note<input value={form.note} onChange={event => setForm({ ...form, note: event.target.value })} placeholder="Optional context" className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></label><button disabled={saving} className="w-full rounded-lg bg-[var(--deep-teal)] py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving...' : 'Save daily stats'}</button>{message && <p className="text-xs text-[var(--bright-teal)]">{message}</p>}</form>
      <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm overflow-hidden"><div className="px-5 py-4 border-b border-[var(--border)]"><h2 className="font-heading text-lg text-[var(--deep-teal)]">Daily History</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-[var(--light-mint)] text-[10px] uppercase tracking-wide text-[var(--muted-foreground)]"><th className="text-left px-4 py-2.5">Date</th><th className="text-left px-4 py-2.5">Channel</th><th className="text-right px-4 py-2.5">Followers</th><th className="text-right px-4 py-2.5">Impressions</th><th className="text-right px-4 py-2.5">Views</th><th className="text-left px-4 py-2.5">Source</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{stats.slice(0, 30).map(stat => <tr key={`${stat.channel_id}-${stat.logged_on}`}><td className="px-4 py-2.5">{stat.logged_on}</td><td className="px-4 py-2.5">{BRAND_CHANNELS.find(channel => channel.id === stat.channel_id)?.name || stat.channel_id}</td><td className="px-4 py-2.5 text-right">{number(stat.followers)}</td><td className="px-4 py-2.5 text-right">{number(stat.impressions)}</td><td className="px-4 py-2.5 text-right">{number(stat.views)}</td><td className="px-4 py-2.5 text-xs capitalize text-[var(--muted-foreground)]">{stat.source}</td></tr>)}{stats.length === 0 && <tr><td colSpan={6} className="px-4 py-12 text-center text-sm text-[var(--muted-foreground)]">No stats logged yet. Add your first snapshot below.</td></tr>}</tbody></table></div></div>
    </div>
  </div></div>
}

function ChannelCard({ channel, history, connected }: { channel: typeof BRAND_CHANNELS[number]; history: Stat[]; connected: boolean }) {
  const Icon = icons[channel.platform] || BarChart3
  const latest = history.at(-1)
  const prior = history.at(-2)
  const growth = latest && prior && latest.followers !== null && prior.followers !== null ? latest.followers - prior.followers : null
  const points = history.slice(-14).map(item => item.followers || 0)
  const max = Math.max(...points, 1), min = Math.min(...points, 0), range = Math.max(max - min, 1)
  const line = points.length > 1 ? points.map((point, index) => `${index / (points.length - 1) * 100},${88 - ((point - min) / range) * 68}`).join(' ') : ''
  return <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm p-5 min-h-[255px]"><div className="flex justify-between gap-4"><div className="flex gap-3"><div className="relative w-10 h-10 rounded-xl overflow-hidden flex items-center justify-center text-white" style={{ background: channel.color }}>{channel.avatar ? <Image src={channel.avatar} alt={`${channel.name} profile`} fill sizes="40px" className="object-cover" /> : <Icon size={19} />}</div><div><p className="font-semibold text-[var(--foreground)] leading-tight">{channel.name}</p><p className="text-xs text-[var(--muted-foreground)] mt-0.5">{channel.platform}</p></div></div>{channel.url && <a href={channel.url} target="_blank" rel="noreferrer" className="text-[var(--muted-foreground)] hover:text-[var(--deep-teal)]"><ExternalLink size={16} /></a>}</div><div className="mt-5 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-wide text-[var(--muted-foreground)]">Followers</p><p className="text-3xl font-semibold text-[var(--deep-teal)] mt-0.5">{latest ? number(latest.followers) : '—'}</p></div>{growth !== null && <span className={growth >= 0 ? 'text-xs font-semibold text-emerald-600 bg-emerald-50 rounded-full px-2 py-1' : 'text-xs font-semibold text-red-600 bg-red-50 rounded-full px-2 py-1'}>{growth >= 0 ? '+' : ''}{number(growth)} since prior log</span>}</div><div className="h-[67px] mt-4 bg-[var(--light-mint)]/40 rounded-xl overflow-hidden">{line ? <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="w-full h-full"><polyline fill="none" stroke={channel.color} strokeWidth="3" vectorEffect="non-scaling-stroke" points={line} /></svg> : <div className="h-full flex items-center justify-center text-xs text-[var(--muted-foreground)]">Log two days to see growth</div>}</div><div className="grid grid-cols-2 gap-3 mt-4 text-xs"><div><p className="text-[var(--muted-foreground)]">Impressions</p><p className="font-semibold mt-0.5">{latest ? number(latest.impressions) : '—'}</p></div><div><p className="text-[var(--muted-foreground)]">Views</p><p className="font-semibold mt-0.5">{latest ? number(latest.views) : '—'}</p></div></div>{channel.id.startsWith('youtube') && <a href={`/api/auth/youtube?channel=${channel.id}`} className="inline-block mt-4 text-xs font-semibold text-[var(--bright-teal)] hover:underline">{connected ? 'Reconnect YouTube' : 'Connect YouTube'}</a>}</div>
}
