'use client'

import { FormEvent, useMemo, useState } from 'react'
import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { BarChart3, ExternalLink, Instagram, Linkedin, Mail, Mic2, RefreshCw, Users, Youtube } from 'lucide-react'
import { BRAND_CHANNELS } from '@/lib/brand-channels'

type Stat = { channel_id: string; logged_on: string; followers: number | null; impressions: number | null; views: number | null; source: string; note: string | null }
const ranges = [{ label: '24H', days: 1 }, { label: '48H', days: 2 }, { label: '7D', days: 7 }, { label: '14D', days: 14 }, { label: '30D', days: 30 }, { label: '60D', days: 60 }, { label: '90D', days: 90 }]
const icons: Record<string, typeof Youtube> = { YouTube: Youtube, Instagram, LinkedIn: Linkedin, Podcast: Mic2, Community: Users, Newsletter: Mail, Substack: Mail, X: BarChart3 }
const number = (value: number | null | undefined) => new Intl.NumberFormat('en-US', { notation: value && Math.abs(value) >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value || 0)
const percent = (current: number | null, previous: number | null) => !current || previous === null || previous === 0 ? null : ((current - previous) / previous) * 100

export function BrandStatsClient({ stats, connectedChannels }: { stats: Stat[]; connectedChannels: string[] }) {
  const router = useRouter()
  const [windowDays, setWindowDays] = useState(14)
  const [form, setForm] = useState({ channel_id: 'linkedin', logged_on: new Date().toISOString().slice(0, 10), followers: '', impressions: '', views: '', note: '' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [refreshing, setRefreshing] = useState(false)
  const [animationKey, setAnimationKey] = useState(0)
  const cutoff = new Date(Date.now() - (windowDays - 1) * 86400000).toISOString().slice(0, 10)
  const filteredStats = stats.filter(stat => stat.logged_on >= cutoff)
  const byChannel = useMemo(() => BRAND_CHANNELS.map(channel => ({ channel, history: filteredStats.filter(stat => stat.channel_id === channel.id).sort((a, b) => a.logged_on.localeCompare(b.logged_on)) })), [filteredStats])
  const dates = [...new Set(filteredStats.map(stat => stat.logged_on))].sort().reverse()
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch('/api/brand-stats/manual', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); setMessage(response.ok ? 'Saved. Click Refresh stats to display it.' : 'Could not save this entry.') }
  const refresh = async () => { setRefreshing(true); await fetch('/api/brand-stats/refresh', { method: 'POST' }); setAnimationKey(value => value + 1); router.refresh(); setRefreshing(false) }

  return <div className="min-h-screen bg-[var(--background)] py-6 px-4"><div className="max-w-[1500px] mx-auto space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[var(--bright-teal)] font-semibold">MMG Homebase</p><h1 className="font-heading text-3xl text-[var(--deep-teal)] mt-1">Brand Stats</h1><p className="text-sm text-[var(--muted-foreground)] mt-1">Daily audience, impressions, and views across your brand.</p></div><button onClick={refresh} disabled={refreshing} className="flex items-center gap-2 rounded-xl bg-[var(--deep-teal)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw size={16} className={refreshing ? 'animate-spin' : ''} />{refreshing ? 'Refreshing...' : 'Refresh stats'}</button></div>
    <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm px-4 py-3 flex flex-wrap gap-2 items-center"><span className="text-[10px] uppercase tracking-wide font-semibold text-[var(--muted-foreground)] mr-1">Growth window</span>{ranges.map(range => <button key={range.days} onClick={() => { setWindowDays(range.days); setAnimationKey(value => value + 1) }} className={windowDays === range.days ? 'rounded-md bg-[var(--dark-navy)] px-3 py-1.5 text-xs font-semibold text-white' : 'rounded-md bg-[var(--light-mint)] px-3 py-1.5 text-xs font-semibold text-[var(--deep-teal)] hover:bg-[var(--bright-teal)] hover:text-white'}>{range.label}</button>)}</div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{byChannel.map(({ channel, history }) => <ChannelCard key={channel.id} channel={channel} history={history} connected={connectedChannels.includes(channel.id)} animationKey={animationKey} />)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[0.95fr_2.05fr] gap-5"><form onSubmit={submit} className="bg-white rounded-2xl border border-[var(--border)] shadow-sm p-5 space-y-4"><div><h2 className="font-heading text-lg text-[var(--deep-teal)]">Log Daily Stats</h2><p className="text-xs text-[var(--muted-foreground)] mt-1">Add a new daily snapshot for any channel.</p></div><label className="block text-xs font-medium">Channel<select value={form.channel_id} onChange={event => setForm({ ...form, channel_id: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm">{BRAND_CHANNELS.map(channel => <option key={channel.id} value={channel.id}>{channel.name} · {channel.platform}</option>)}</select></label><label className="block text-xs font-medium">Date<input type="date" value={form.logged_on} onChange={event => setForm({ ...form, logged_on: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></label><div className="grid grid-cols-3 gap-2">{(['followers', 'impressions', 'views'] as const).map(field => <label key={field} className="block text-xs font-medium capitalize">{field}<input type="number" min="0" value={form[field]} onChange={event => setForm({ ...form, [field]: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] px-2 py-2 text-sm" /></label>)}</div><label className="block text-xs font-medium">Note<input value={form.note} onChange={event => setForm({ ...form, note: event.target.value })} placeholder="Optional context" className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></label><button disabled={saving} className="w-full rounded-lg bg-[var(--deep-teal)] py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving...' : 'Save daily stats'}</button>{message && <p className="text-xs text-[var(--bright-teal)]">{message}</p>}</form>
      <DailyTable dates={dates} stats={filteredStats} />
    </div>
  </div></div>
}

function ChannelCard({ channel, history, connected, animationKey }: { channel: typeof BRAND_CHANNELS[number]; history: Stat[]; connected: boolean; animationKey: number }) {
  const Icon = icons[channel.platform] || BarChart3
  const latest = history.at(-1), first = history[0]
  const growth = latest && first ? percent(latest.followers, first.followers) : null
  const points = history.map(item => item.followers || 0), max = Math.max(...points, 1), min = Math.min(...points, 0), range = Math.max(max - min, 1)
  const line = points.length > 1 ? points.map((point, index) => `${index / (points.length - 1) * 100},${88 - ((point - min) / range) * 68}`).join(' ') : ''
  return <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm p-5 min-h-[255px]"><div className="flex justify-between gap-4"><div className="flex gap-3"><div className="relative w-10 h-10 rounded-xl overflow-hidden flex items-center justify-center text-white" style={{ background: channel.color }}>{channel.avatar ? <Image src={channel.avatar} alt={`${channel.name} profile`} fill sizes="40px" className="object-cover" /> : <Icon size={19} />}</div><div><p className="font-semibold text-[var(--foreground)] leading-tight">{channel.name}</p><p className="text-xs text-[var(--muted-foreground)] mt-0.5">{channel.platform}</p></div></div>{channel.url && <a href={channel.url} target="_blank" rel="noreferrer" className="text-[var(--muted-foreground)] hover:text-[var(--deep-teal)]"><ExternalLink size={16} /></a>}</div><div className="mt-5 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-wide text-[var(--muted-foreground)]">{channel.audienceLabel || 'Followers'}</p><p className="text-3xl font-semibold text-[var(--deep-teal)] mt-0.5">{latest ? number(latest.followers) : '—'}</p></div>{growth !== null && <span className={growth >= 0 ? 'text-xs font-semibold text-emerald-600 bg-emerald-50 rounded-full px-2 py-1' : 'text-xs font-semibold text-red-600 bg-red-50 rounded-full px-2 py-1'}>{growth >= 0 ? '+' : ''}{growth.toFixed(2)}%</span>}</div><div className="h-[67px] mt-4 bg-[var(--light-mint)]/40 rounded-xl overflow-hidden">{line ? <svg key={animationKey} viewBox="0 0 100 100" preserveAspectRatio="none" className="w-full h-full animate-[pulse_0.55s_ease-in-out]"><polyline fill="none" stroke={channel.color} strokeWidth="3" vectorEffect="non-scaling-stroke" points={line} /></svg> : <div className="h-full flex items-center justify-center text-xs text-[var(--muted-foreground)]">Log two days to see growth</div>}</div><div className={`grid ${channel.hideViews ? 'grid-cols-1' : 'grid-cols-2'} gap-3 mt-4 text-xs`}><div><p className="text-[var(--muted-foreground)]">{channel.impressionsLabel || 'Impressions'}</p><p className="font-semibold mt-0.5">{latest ? number(latest.impressions) : '—'}</p></div>{!channel.hideViews && <div><p className="text-[var(--muted-foreground)]">Views</p><p className="font-semibold mt-0.5">{latest ? number(latest.views) : '—'}</p></div>}</div>{channel.id.startsWith('youtube') && <a href={`/api/auth/youtube?channel=${channel.id}`} className="inline-block mt-4 text-xs font-semibold text-[var(--bright-teal)] hover:underline">{connected ? 'Reconnect YouTube' : 'Connect YouTube'}</a>}</div>
}

function DailyTable({ dates, stats }: { dates: string[]; stats: Stat[] }) {
  const get = (date: string, channelId: string) => stats.find(stat => stat.logged_on === date && stat.channel_id === channelId)
  const previous = (date: string, channelId: string) => stats.filter(stat => stat.channel_id === channelId && stat.logged_on < date).sort((a, b) => b.logged_on.localeCompare(a.logged_on))[0]
  return <div className="bg-white rounded-2xl border border-[var(--border)] shadow-sm overflow-hidden"><div className="px-5 py-4 border-b border-[var(--border)]"><h2 className="font-heading text-lg text-[var(--deep-teal)]">Daily Stats</h2><p className="text-xs text-[var(--muted-foreground)] mt-1">Each value includes day-over-day audience growth when a prior log exists.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="bg-[var(--light-mint)] text-[10px] uppercase tracking-wide text-[var(--muted-foreground)]"><th className="sticky left-0 bg-[var(--light-mint)] text-left px-4 py-2.5">Date</th>{BRAND_CHANNELS.map(channel => <th key={channel.id} className="px-3 py-2.5 text-left min-w-[130px]"><span className="flex items-center gap-1.5"><span className="relative block w-4 h-4 rounded overflow-hidden" style={{ background: channel.color }}>{channel.avatar && <Image src={channel.avatar} alt="" fill sizes="16px" className="object-cover" />}</span>{channel.name}</span></th>)}</tr></thead><tbody className="divide-y divide-[var(--border)]">{dates.map(date => <tr key={date}><td className="sticky left-0 bg-white px-4 py-3 text-xs font-medium">{date}</td>{BRAND_CHANNELS.map(channel => { const stat = get(date, channel.id), prior = previous(date, channel.id), change = stat ? percent(stat.followers, prior?.followers ?? null) : null; return <td key={channel.id} className="px-3 py-3 align-top"><p className="font-semibold">{stat ? number(stat.followers) : '—'}</p>{change !== null && <p className={change >= 0 ? 'text-[10px] text-emerald-600' : 'text-[10px] text-red-600'}>{change >= 0 ? '+' : ''}{change.toFixed(2)}% DoD</p>}</td> })}</tr>)}{dates.length === 0 && <tr><td colSpan={BRAND_CHANNELS.length + 1} className="px-4 py-12 text-center text-sm text-[var(--muted-foreground)]">No stats logged in this selected period.</td></tr>}</tbody></table></div></div>
}
